/** Field definitions for the settings sections served by GET/PUT /settings/:section. */
export const SETTINGS_FIELDS = {
  general: [
    { name: 'h-business', type: 'heading', label: 'Business details' },
    { name: 'businessName', label: 'Business name', required: true },
    { name: 'tradingName', label: 'Registered / trading name' },
    { name: 'registrationNumber', label: 'Company registration number' },
    { name: 'vatNumber', label: 'VAT number' },
    { name: 'email', label: 'Email', type: 'email', required: true },
    { name: 'phone', label: 'Telephone', type: 'tel' },
    { name: 'address', label: 'Address', type: 'textarea', rows: 2, span: 12 },
    { name: 'h-locale', type: 'heading', label: 'Locale' },
    { name: 'currency', label: 'Currency', type: 'select', required: true, options: [{ value: 'ZAR', label: 'South African Rand (ZAR)' }] },
    { name: 'timezone', label: 'Time zone', type: 'select', required: true, options: [{ value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (SAST)' }] },
  ],
  invoice: [
    { name: 'h-numbering', type: 'heading', label: 'Numbering' },
    { name: 'invoicePrefix', label: 'Invoice prefix', required: true, span: 4 },
    { name: 'quotePrefix', label: 'Quote prefix', required: true, span: 4 },
    { name: 'proformaPrefix', label: 'Pro forma prefix', required: true, span: 4 },
    { name: 'h-defaults', type: 'heading', label: 'Defaults' },
    { name: 'defaultDueDays', label: 'Payment terms (days)', type: 'number', min: 0, span: 4 },
    { name: 'quoteValidityDays', label: 'Quote validity (days)', type: 'number', min: 1, span: 4 },
    { name: 'defaultVatRate', label: 'Default VAT rate (%)', type: 'number', min: 0, max: 100, span: 4 },
    { name: 'showVatBreakdown', label: 'Show VAT breakdown on invoices', type: 'switch', span: 12 },
    { name: 'h-print', type: 'heading', label: 'Printed invoice' },
    { name: 'bankingDetails', label: 'Banking details', type: 'textarea', rows: 2, span: 12 },
    { name: 'footerText', label: 'Footer text', type: 'textarea', rows: 2, span: 12 },
  ],
  product: [
    { name: 'skuPrefix', label: 'SKU prefix' },
    { name: 'defaultProductType', label: 'Default product type', type: 'select', options: 'productType', required: true },
    { name: 'defaultReorderLevel', label: 'Default reorder level', type: 'number', min: 0 },
    { name: 'requireSerialsForHearingAids', label: 'Require serial numbers when receiving hearing aids', type: 'switch', span: 12 },
    { name: 'allowNegativeStock', label: 'Allow negative stock (backend enforced)', type: 'switch', span: 12 },
  ],
  system: [
    { name: 'sessionTimeoutMinutes', label: 'Session timeout (minutes)', type: 'number', min: 5 },
    { name: 'dateFormat', label: 'Date format', type: 'select', options: ['DD/MM/YYYY', 'YYYY-MM-DD', 'DD MMM YYYY'].map((v) => ({ value: v, label: v })) },
    { name: 'auditLogRetentionDays', label: 'Audit log retention (days)', type: 'number', min: 30 },
    { name: 'enableEmailNotifications', label: 'Email notifications', type: 'switch', span: 12 },
    { name: 'enableWhatsapp', label: 'WhatsApp integration', type: 'switch', span: 12, hint: 'Requires the backend WhatsApp Business integration.' },
  ],
};
