import { col, statusField, statusFilter } from '../../components/resource/columns';
import { Badge, StatusBadge } from '../../components/ui';
import { optionLabel } from '../../config/statuses';

export const warehousesConfig = {
  resource: 'warehouses',
  title: 'Warehouses',
  singular: 'Warehouse',
  eyebrow: 'Inventory',
  description: 'Each branch has one or more warehouses, e.g. Main Stock and Broken Stock.',
  permissions: { create: 'branches.create', edit: 'branches.edit', delete: 'branches.delete' },
  columns: [
    { key: 'name', header: 'Warehouse', sortable: true, render: (r) => <span className="row"><strong>{r.name}</strong>{r.isDefault && <Badge tone="brand">Default</Badge>}</span> },
    col.text('branchName', 'Branch'),
    { key: 'type', header: 'Type', sortable: true, render: (r) => optionLabel('warehouseType', r.type) },
    col.text('description', 'Description', { sortable: false }),
    col.status(),
  ],
  filters: [
    { key: 'branchId', label: 'Branches', options: { resource: 'branches' } },
    { key: 'type', label: 'Types', options: 'warehouseType' },
    statusFilter(),
  ],
  fields: [
    { name: 'name', label: 'Warehouse name', required: true, placeholder: 'e.g. Main Stock' },
    { name: 'branchId', label: 'Branch', type: 'select', required: true, options: { resource: 'branches' } },
    { name: 'type', label: 'Warehouse type', type: 'select', required: true, options: 'warehouseType' },
    statusField(),
    { name: 'description', label: 'Description', type: 'textarea', span: 12 },
    { name: 'isDefault', label: 'Default', type: 'switch', switchLabel: 'Default warehouse for this branch (used on new invoices)', span: 12 },
  ],
  defaultValues: { type: 'main', isDefault: false },
  formSize: 'md',
  viewItems: (r) => [
    { label: 'Branch', value: r.branchName },
    { label: 'Type', value: optionLabel('warehouseType', r.type) },
    { label: 'Default warehouse', value: r.isDefault ? 'Yes' : 'No' },
    { label: 'Description', value: r.description },
    { label: 'Status', value: <StatusBadge value={r.status} /> },
  ],
};

export const branchesConfig = {
  resource: 'branches',
  title: 'Branches',
  singular: 'Branch',
  eyebrow: 'Administration',
  description: 'Physical store locations. Each branch has warehouses, assigned users and optional practice information.',
  permissions: { create: 'branches.create', edit: 'branches.edit', delete: 'branches.delete' },
  detailPath: (r) => `/branches/${r.id}`,
  columns: [
    col.entity('name', 'Branch', 'code'),
    col.text('city', 'City'),
    col.text('managerName', 'Store manager'),
    col.text('warehouseCount', 'Warehouses', { align: 'right' }),
    col.text('practiceName', 'Practice'),
    col.status(),
  ],
  filters: [statusFilter()],
  fields: [
    { name: 'name', label: 'Branch name', required: true },
    { name: 'code', label: 'Branch code', required: true, placeholder: 'e.g. DBV' },
    { name: 'phone', label: 'Telephone', type: 'tel' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'address', label: 'Street address', span: 8 },
    { name: 'city', label: 'City', span: 4 },
    { name: 'practiceId', label: 'Practice', type: 'select', options: { resource: 'practices' }, hint: 'Practice details used on invoices and medical aid claims' },
    statusField(),
  ],
};

export const practicesConfig = {
  resource: 'practices',
  title: 'Practices',
  singular: 'Practice',
  eyebrow: 'Administration',
  description: 'Practice information used on invoices and medical aid claims. Kept separate from branches because it can vary.',
  permissions: branchesConfig.permissions,
  columns: [
    col.strong('name', 'Practice'),
    col.mono('practiceNumber', 'Practice no.'),
    col.text('practitionerName', 'Practitioner'),
    col.text('branchName', 'Branch'),
    col.status(),
  ],
  filters: [{ key: 'branchId', label: 'Branches', options: { resource: 'branches' } }, statusFilter()],
  fields: [
    { name: 'name', label: 'Practice name', required: true, span: 12 },
    { name: 'practiceNumber', label: 'Practice number (BHF)', required: true },
    { name: 'hpcsaNumber', label: 'HPCSA registration' },
    { name: 'practitionerName', label: 'Treating practitioner' },
    { name: 'vatNumber', label: 'VAT number' },
    { name: 'branchId', label: 'Associated branch', type: 'select', options: { resource: 'branches' } },
    { name: 'email', label: 'Claims email', type: 'email' },
    { name: 'phone', label: 'Telephone', type: 'tel' },
    statusField(),
    { name: 'address', label: 'Address', type: 'textarea', rows: 2, span: 12 },
    { name: 'bankingDetails', label: 'Banking details (shown on invoices)', type: 'textarea', rows: 2, span: 12 },
  ],
  viewItems: (r) => [
    { label: 'Practice number', value: r.practiceNumber },
    { label: 'HPCSA registration', value: r.hpcsaNumber },
    { label: 'Practitioner', value: r.practitionerName },
    { label: 'VAT number', value: r.vatNumber },
    { label: 'Branch', value: r.branchName },
    { label: 'Claims email', value: r.email },
    { label: 'Telephone', value: r.phone },
    { label: 'Address', value: r.address },
    { label: 'Banking details', value: r.bankingDetails },
    { label: 'Status', value: <StatusBadge value={r.status} /> },
  ],
};

export const suppliersConfig = {
  resource: 'suppliers',
  title: 'Suppliers',
  singular: 'Supplier',
  eyebrow: 'Relationships',
  description: 'Who you purchase stock from. Suppliers are separate from the companies that manufacture products.',
  permissions: { create: 'purchases.create', edit: 'purchases.edit', delete: 'purchases.edit' },
  columns: [
    col.entity('name', 'Supplier', 'contactPerson'),
    col.text('email', 'Email'),
    col.text('phone', 'Telephone'),
    col.mono('vatNumber', 'VAT number'),
    col.status(),
  ],
  filters: [statusFilter()],
  fields: [
    { name: 'h-company', type: 'heading', label: 'Supplier' },
    { name: 'name', label: 'Supplier name', required: true, span: 12 },
    { name: 'contactPerson', label: 'Contact person' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'phone', label: 'Telephone', type: 'tel' },
    { name: 'vatNumber', label: 'VAT number' },
    { name: 'registrationNumber', label: 'Company registration' },
    statusField(),
    { name: 'address', label: 'Address', type: 'textarea', rows: 2, span: 12 },
    { name: 'h-bank', type: 'heading', label: 'Banking details' },
    { name: 'bankName', label: 'Bank', span: 4 },
    { name: 'accountNumber', label: 'Account number', span: 4 },
    { name: 'branchCode', label: 'Branch code', span: 4 },
    { name: 'notes', label: 'Notes', type: 'textarea', rows: 3, span: 12 },
  ],
  viewItems: (r) => [
    { label: 'Contact person', value: r.contactPerson },
    { label: 'Email', value: r.email },
    { label: 'Telephone', value: r.phone },
    { label: 'VAT number', value: r.vatNumber },
    { label: 'Company registration', value: r.registrationNumber },
    { label: 'Address', value: r.address },
    { label: 'Bank', value: [r.bankName, r.accountNumber, r.branchCode].filter(Boolean).join(' · ') },
    { label: 'Notes', value: r.notes },
    { label: 'Status', value: <StatusBadge value={r.status} /> },
  ],
};
